FROM node:8.16.2-alpine                                                               

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install -D

# Build app
COPY . .
RUN npm run build && \
    npm prune --production && \
    rm -r package* public/ src/

# Run it
ENTRYPOINT npm run start
