FROM node:8.16.2-alpine                                                               

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install -D

# Build app
COPY . .
RUN npm run build

# Clean up
RUN npm uninstall -D
RUN rm -rf src/ & rm -rf public/

# Run it
ENTRYPOINT npm run start
